import { describe, expect, it } from "vitest";
import { FaceTracker } from "@/lib/perception/kalman";

describe("FaceTracker (Kalman filter)", () => {
  it("starts prediction at the origin", () => {
    const tracker = new FaceTracker();
    const { x, y } = tracker.predict();
    expect(x).toBe(0);
    expect(y).toBe(0);
  });

  it("converges to a stationary point", () => {
    const tracker = new FaceTracker();
    const target = { x: 100, y: 200 };

    let last = { x: 0, y: 0 };
    for (let i = 0; i < 50; i++) {
      tracker.predict();
      last = tracker.correct(target.x, target.y);
    }

    expect(Math.abs(last.x - target.x)).toBeLessThan(1);
    expect(Math.abs(last.y - target.y)).toBeLessThan(1);
  });

  it("damps a single outlier measurement instead of fully following it", () => {
    const tracker = new FaceTracker();
    const target = { x: 50, y: 50 };

    // Settle near the target first.
    for (let i = 0; i < 20; i++) {
      tracker.predict();
      tracker.correct(target.x, target.y);
    }

    tracker.predict();
    const jumped = tracker.correct(500, 500);

    const rawJumpDistance = Math.hypot(500 - target.x, 500 - target.y);
    const smoothedJumpDistance = Math.hypot(jumped.x - target.x, jumped.y - target.y);

    expect(smoothedJumpDistance).toBeLessThan(rawJumpDistance * 0.5);
  });

  // Cross-language parity fixture: generated by running the actual
  // cv2.KalmanFilter-backed perception/tracking.py FaceTracker on this exact
  // measurement sequence (see frontend/tests/unit/kalman.test.ts history for
  // the generating snippet). If this ever fails, the TS port has drifted
  // from the real OpenCV math, not just from another reimplementation of it.
  it("matches perception/tracking.py's cv2.KalmanFilter output bit-for-bit (within float32 tolerance)", () => {
    const measurements: [number, number][] = [
      [10.0, 12.0],
      [10.5, 11.8],
      [11.0, 11.5],
      [40.0, 40.0],
      [11.5, 11.2],
      [11.6, 11.1],
      [11.55, 11.05],
      [11.5, 11.0],
    ];

    const expected = [
      { predict: [0.0, 0.0], correct: [6.69966983795166, 8.039604187011719] },
      { predict: [10.0, 12.0], correct: [10.336601257324219, 11.86535930633545] },
      {
        predict: [13.805232048034668, 15.758435249328613],
        correct: [12.016509056091309, 13.043094635009766],
      },
      {
        predict: [14.753386497497559, 15.825345039367676],
        correct: [29.545185089111328, 29.989093780517578],
      },
      {
        predict: [37.366661071777344, 37.640052795410156],
        correct: [23.386011123657227, 23.349491119384766],
      },
      {
        predict: [26.9411563873291, 26.63954734802246],
        correct: [19.162067413330078, 18.75986099243164],
      },
      {
        predict: [20.499454498291016, 19.803478240966797],
        correct: [16.158037185668945, 15.557129859924316],
      },
      {
        predict: [16.29500961303711, 15.426620483398438],
        correct: [14.031190872192383, 13.336725234985352],
      },
    ];

    const tracker = new FaceTracker();
    // float32 round-trip in OpenCV loses precision relative to JS's float64
    // math, so we allow a small absolute tolerance rather than exact equality.
    const TOLERANCE = 0.1;

    measurements.forEach(([mx, my], i) => {
      const predicted = tracker.predict();
      const corrected = tracker.correct(mx, my);

      expect(Math.abs(predicted.x - expected[i].predict[0])).toBeLessThan(TOLERANCE);
      expect(Math.abs(predicted.y - expected[i].predict[1])).toBeLessThan(TOLERANCE);
      expect(Math.abs(corrected.x - expected[i].correct[0])).toBeLessThan(TOLERANCE);
      expect(Math.abs(corrected.y - expected[i].correct[1])).toBeLessThan(TOLERANCE);
    });
  });
});
