"""Converts blink_classifier.tflite into a C header (firmware/include/model_data.h)
that TensorFlow Lite Micro can load on the ESP32, replacing the original
firmware's undefined `your_model_data` placeholder symbol with a real,
generated array.

Usage:
    python tinyml/convert_to_c_array.py
"""

from pathlib import Path

INPUT_TFLITE = Path(__file__).parent / "blink_classifier.tflite"
OUTPUT_HEADER = Path(__file__).parent.parent / "firmware" / "include" / "model_data.h"


def main() -> None:
    model_bytes = INPUT_TFLITE.read_bytes()

    lines = [
        "// Auto-generated by tinyml/convert_to_c_array.py — do not edit by hand.",
        "// Source: tinyml/blink_classifier.tflite",
        "#ifndef MODEL_DATA_H_",
        "#define MODEL_DATA_H_",
        "",
        "#include <cstdint>",
        "",
        f"const unsigned int g_blink_model_len = {len(model_bytes)};",
        "alignas(8) const unsigned char g_blink_model_data[] = {",
    ]

    for i in range(0, len(model_bytes), 12):
        chunk = model_bytes[i : i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    lines += ["};", "", "#endif  // MODEL_DATA_H_", ""]

    OUTPUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_HEADER.write_text("\n".join(lines))
    print(f"Wrote {len(model_bytes)} bytes as C array to {OUTPUT_HEADER}")


if __name__ == "__main__":
    main()
